experiment_name: "test"
output_base_dir: "outputs/experiments/renew"
data_source_base_dir: "dataset/10fold_npy"
folds: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]
workers: 10

Nu: 256
Ny: 3
Nx: [70]
input_scale: [0.001]
density: [0.5]
rho: [0.9]
