experiment_name: "test"
output_dir: ["outputs/experiments/renew/a",
             "outputs/experiments/renew/b",
             "outputs/experiments/renew/c",
             "outputs/experiments/renew/d",
             "outputs/experiments/renew/e",
             "outputs/experiments/renew/f",
             "outputs/experiments/renew/g",
             "outputs/experiments/renew/h",
             "outputs/experiments/renew/i",
             "outputs/experiments/renew/j"]

data_source: ["dataset/10fold_npy/a",
              "dataset/10fold_npy/b",
              "dataset/10fold_npy/c",
              "dataset/10fold_npy/d",
              "dataset/10fold_npy/e",
              "dataset/10fold_npy/f",
              "dataset/10fold_npy/g",
              "dataset/10fold_npy/h",
              "dataset/10fold_npy/i",
              "dataset/10fold_npy/j"]
workers: 10

Nu: 256
Ny: 3
Nx: [70]
input_scale: [0.001]
density: [0.5]
rho: [0.9]
